global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (系统监控)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # 微服务监控
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'competitor-service'
    static_configs:
      - targets: ['competitor-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'optimization-service'
    static_configs:
      - targets: ['optimization-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8005']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'asynq-monitor'
    static_configs:
      - targets: ['asynq-monitor:5555']
    metrics_path: '/metrics'
    scrape_interval: 30s
