// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	"amazonpilot/internal/optimization/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/health",
					Handler: healthHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/ping",
					Handler: pingHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/optimization"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/stats",
					Handler: getOptimizationStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/tasks",
					Handler: createOptimizationTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tasks",
					Handler: listOptimizationTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tasks/:task_id",
					Handler: getOptimizationTaskHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/optimization"),
	)
}
