name: Amazon Pilot - SSH Test

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Simple SSH Test
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "=== SSH Test Start ==="
          date
          pwd
          whoami
          echo "Creating test file..."
          echo "GitHub CI SSH Test executed at $(date)" > /tmp/ssh-test-simple.log
          echo "=== SSH Test End ==="