version: '3.8'

services:
  # TimescaleDB (基于PostgreSQL，优化时序数据)
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: amazon-pilot-timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_DB: amazon_pilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: amazon123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - amazon-pilot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d amazon_pilot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (缓存层)
  redis:
    image: redis:7-alpine
    container_name: amazon-pilot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - amazon-pilot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  # Redis Commander (Redis管理界面)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: amazon-pilot-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - amazon-pilot-network
    depends_on:
      - redis

  # pgAdmin (PostgreSQL管理界面)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: amazon-pilot-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@amazon-pilot.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"  # pgAdmin 标准端口
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - amazon-pilot-network
    depends_on:
      - timescaledb

  # Prometheus (指标收集)
  prometheus:
    image: prom/prometheus:latest
    container_name: amazon-pilot-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    networks:
      - amazon-pilot-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'

  # Loki (日志聚合)
  loki:
    image: grafana/loki:latest
    container_name: amazon-pilot-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    networks:
      - amazon-pilot-network
    command: -config.file=/etc/loki/local-config.yaml

  # Promtail (日志采集器)
  promtail:
    image: grafana/promtail:latest
    container_name: amazon-pilot-promtail
    restart: unless-stopped
    volumes:
      - ./monitoring/promtail.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro  # 系统日志
      - ./logs:/var/app/logs:ro  # 应用日志目录
    networks:
      - amazon-pilot-network
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  # Grafana (可视化面板)
  grafana:
    image: grafana/grafana:latest
    container_name: amazon-pilot-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"  # Grafana 使用默认端口
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - amazon-pilot-network
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - prometheus
      - loki

volumes:
  timescaledb_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
  prometheus_data:
    driver: local
  loki_data:
    driver: local
  grafana_data:
    driver: local

networks:
  amazon-pilot-network:
    driver: bridge